### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by ram1505** [zainozzaini/RaspberryPi-Jasper-LED#2]
Hi,
I cannot get the light ON, OFF, Blinking on my Pi. I followed the instructions on the GitHub. Jasper recognizes my keywords and responds back. However, the light is not turning ON or OFF. What am I doing wrong? FYI, I've a working LED. I've tried connecting in both GPIO7 and GPIO4.

**Comment by zainozzaini** [comment]
Are you sure have connected to Ground (GND) pin too ?

**Comment by Legend23** [comment]
For my part, Jasper can't recognize the word "Light" . So I can't test it... :/ 

What can I do ?

**Comment by Legend23** [comment]
I have this error " error in main block " what's the problem ?

**Comment by zainozzaini** [comment]
Hi Legend23..  could u give me the full error log.. Thanks
