### ISSUE TITLE
SWITCH command

### ISSUE THREAD

**Issue by ucy74** [zainozzaini/RaspberryPi-Jasper-LED#3]
I was run your code with Jasper on an old broken tablet with Debian.
Works OK with "light on", "light off", "blinking" commands, but word "switch" does nothing.
Is this word unused as standalone, or needs special phrase?

Same guestions of blinking count and sleep time parameters.
How the spell is?

**Comment by zainozzaini** [comment]
Hi @ucy74. Thanks for comment out. Yes the 'SWITCH' command is not in re.search. Sorry for that, because I forgot to not put it in the WORDS list. Will fix. Thanks
